# CMake generated Testfile for 
# Source directory: /home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests
# Build directory: /home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMake.List "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/ListTest.cmake")
add_test(CMake.VariableWatch "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/VariableWatchTest.cmake")
add_test(CMake.Include "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/IncludeTest.cmake")
add_test(CMake.FindBase "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/FindBaseTest.cmake")
add_test(CMake.Toolchain "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/ToolchainTest.cmake")
add_test(CMake.GetFilenameComponentRealpath "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
add_test(CMake.Version "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/VersionTest.cmake")
add_test(CMake.Message "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/MessageTest.cmake")
add_test(CMake.File "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/FileTest.cmake")
add_test(CMake.SeparateArguments "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/SeparateArgumentsTest.cmake")
add_test(CMake.ImplicitLinkInfo "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
add_test(CMake.ModuleNotices "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/ModuleNoticesTest.cmake")
add_test(CMake.GetProperty "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/GetPropertyTest.cmake")
add_test(CMake.If "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/IfTest.cmake")
add_test(CMake.String "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/StringTest.cmake")
add_test(CMake.Math "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/MathTest.cmake")
add_test(CMake.CMakeMinimumRequired "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
add_test(CMake.CompilerIdVendor "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/CompilerIdVendorTest.cmake")
add_test(CMake.ProcessorCount "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-DKWSYS_TEST_EXE=/home/arthur/ros_varient/sim-install/cmake-3.5.1/Source/kwsys/cmsysTestsCxx" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/ProcessorCountTest.cmake")
add_test(CMake.PushCheckState "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/PushCheckStateTest.cmake")
add_test(CMake.While "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/WhileTest.cmake")
add_test(CMake.CMakeHostSystemInformation "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/CMakeHostSystemInformationTest.cmake")
add_test(CMake.FileDownload "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/FileDownloadTest.cmake")
set_tests_properties(CMake.FileDownload PROPERTIES  PASS_REGULAR_EXPRESSION "file already exists with expected MD5 sum")
add_test(CMake.FileDownloadBadHash "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/FileDownloadBadHashTest.cmake")
set_tests_properties(CMake.FileDownloadBadHash PROPERTIES  WILL_FAIL "TRUE")
add_test(CMake.FileUpload "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/FileUploadTest.cmake")
add_test(CMake.ELF "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/ELFTest.cmake")
add_test(CMake.EndStuff "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-Ddir:STRING=/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/EndStuffTest" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/EndStuffTest.cmake")
add_test(CMake.GetPrerequisites "/home/arthur/ros_varient/sim-install/cmake-3.5.1/bin/cmake" "-DCTEST_CONFIGURATION_TYPE:STRING=\${CTEST_CONFIGURATION_TYPE}" "-P" "/home/arthur/ros_varient/sim-install/cmake-3.5.1/Tests/CMakeTests/GetPrerequisitesTest.cmake")
